#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "immich"
name = "Immich"
description.en = "Photo and video backup solution directly from your mobile phone"
description.fr = "Sauvegarde de photos et de vidéos directement depuis votre mobile"

version = "3.0.2~ynh1"

maintainers = ["ewilly"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://immich.app"
demo = "https://demo.immich.app"
admindoc = "https://github.com/immich-app/immich#getting-started"
userdoc = "https://github.com/immich-app/immich#getting-started"
code = "https://github.com/immich-app/immich"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = false
sso = false

disk = "3G"
ram.build = "2G"
ram.runtime = "2G"

[install]
	[install.domain]
	type = "domain"

	[install.init_main_permission]
	help.en = "You must activate 'Visitors' if you want to connect the Immich mobile app to your Immich server. This can be changed later via the webadmin."
	type = "group"
	default = "visitors"

[resources]
	[resources.sources]

	[resources.sources.immich_prebuilt_bookworm]
	amd64.url = "https://github.com/YunoHost-Apps/immich-build/releases/download/immich-v3.0.2/immich-v3.0.2-bookworm-amd64.tar.gz"
	amd64.sha256 = "fd0f2a98bd63b7c39a00fd4b0578a78b13fe3343f5cc55ec6eeb7774836e127a"
	arm64.url = "https://github.com/YunoHost-Apps/immich-build/releases/download/immich-v3.0.2/immich-v3.0.2-bookworm-arm64.tar.gz"
	arm64.sha256 = "e77b7cf441c64bf1ce5e50b07e5910c96a0d919a56cc8586ca35ed60def1960d"

	prefetch = false

	[resources.sources.immich_prebuilt_trixie]
	amd64.url = "https://github.com/YunoHost-Apps/immich-build/releases/download/immich-v3.0.2/immich-v3.0.2-trixie-amd64.tar.gz"
	amd64.sha256 = "461ebf85bd83b1b64f906573aba54e3bd5f8c261bea85ab23900405b9643fc1f"
	arm64.url = "https://github.com/YunoHost-Apps/immich-build/releases/download/immich-v3.0.2/immich-v3.0.2-trixie-arm64.tar.gz"
	arm64.sha256 = "cc4efb6c8f0a2d39de142f2f2c6ba62c05567c9a89f0c7749b764dd3c7795e37"

	prefetch = false

	[resources.sources.vchord]
	# Version https://github.com/immich-app/base-images/blob/main/postgres/versions.yaml
	# and https://github.com/mmomjian/immich/blob/c9e251c78cb606d22ae74f3ec24cae7090756747/server/src/constants.ts#L17
	amd64.url = "https://github.com/tensorchord/VectorChord/releases/download/1.1.1/postgresql-17-vchord_1.1.1-1_amd64.deb"
	amd64.sha256 = "a48132c8d616c0d52a9811b32f12f88a8f6cc8542d7cc0180c8d0986bfbd03c5"
	arm64.url = "https://github.com/tensorchord/VectorChord/releases/download/1.1.1/postgresql-17-vchord_1.1.1-1_arm64.deb"
	arm64.sha256 = "50ae776bb2376f2b21aea646984cef51e96cc8ae49626cceccb043432c3ba1aa"

	format = "whatever"
	extract = false
	rename = "postgresql-17-vchord.deb"
	prefetch = true

	[resources.system_user]

	[resources.install_dir]

	[resources.data_dir]

	[resources.permissions]
	main.url = "/"
	api.url = "/api"
	api.allowed = "visitors"
	api.show_tile = false
	api.protected = true

	[resources.ports]
	main.default = 2283
	machinelearning.default = 3003

	[resources.apt]
	packages = [
		"postgresql",
		"redis-server",
		"uuid-runtime",
		"curl",
		"unzip",
		"libgl1",
		"libglib2.0-0",
		"libexpat1",
		"libexif12",
		"libgif7",
		"libjpeg62-turbo",
		"libpng16-16",
		"libwebp7",
		"libtiff6",
		"libcgif0",
		"liblcms2-2",
		"libaom3",
		"libde265-0",
		"libimagequant0",
		"libwebpdemux2"
	]
	packages_from_raw_bash = """
	if [[ $YNH_DEBIAN_VERSION == "trixie" ]]; then
		echo "libdav1d7, libraw23t64, postgresql-17-pgvector";
	elif [[ $YNH_DEBIAN_VERSION == "bookworm" ]]; then
		echo "libdav1d6, libraw20";
	fi
	"""

	[resources.apt.extras.jellyfin-ffmpeg]
	repo = "deb https://repo.jellyfin.org/debian __YNH_DEBIAN_VERSION__ main"
	key = "https://repo.jellyfin.org/jellyfin_team.gpg.key"
	packages = [
		"jellyfin-ffmpeg7"
	]

	[resources.database]
	type = "postgresql"

	[resources.nodejs]
	version = "24.15.0"
