#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "immich"
name = "Immich"
description.en = "Photo and video backup solution directly from your mobile phone"
description.fr = "Sauvegarde de photos et de vidéos directement depuis votre mobile"

version = "3.1.0~ynh1"

maintainers = ["ewilly"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://immich.app"
demo = "https://demo.immich.app"
admindoc = "https://github.com/immich-app/immich#getting-started"
userdoc = "https://github.com/immich-app/immich#getting-started"
code = "https://github.com/immich-app/immich"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = false
sso = false

disk = "3G"
ram.build = "2G"
ram.runtime = "2G"

[install]
	[install.domain]
	type = "domain"

	[install.init_main_permission]
	help.en = "You must activate 'Visitors' if you want to connect the Immich mobile app to your Immich server. This can be changed later via the webadmin."
	type = "group"
	default = "visitors"

[resources]
	[resources.sources]

	[resources.sources.immich_prebuilt_bookworm]
	amd64.url = "https://github.com/YunoHost-Apps/immich-build/releases/download/immich-v3.1.0/immich-v3.1.0-bookworm-amd64.tar.gz"
	amd64.sha256 = "d71bf6d7efe6e00e5c39a7376fcab9173825a485370f18e5bfc18b536f9426c5"
	arm64.url = "https://github.com/YunoHost-Apps/immich-build/releases/download/immich-v3.1.0/immich-v3.1.0-bookworm-arm64.tar.gz"
	arm64.sha256 = "b3487c4beb06c2702f1317d9c07fff159474a95a147e6f83d2f74f96bb10e802"

	prefetch = false

	[resources.sources.immich_prebuilt_trixie]
	amd64.url = "https://github.com/YunoHost-Apps/immich-build/releases/download/immich-v3.1.0/immich-v3.1.0-trixie-amd64.tar.gz"
	amd64.sha256 = "5f4b3eeefcc8b102bc63795b2a5297de1292cee53092a969dcf0033187b74af5"
	arm64.url = "https://github.com/YunoHost-Apps/immich-build/releases/download/immich-v3.1.0/immich-v3.1.0-trixie-arm64.tar.gz"
	arm64.sha256 = "1244632bb39b4f8a593c52c6264ed6795ea4ca4b6635d6cd8bbfacf1c63298eb"

	prefetch = false

	[resources.sources.vchord]
	# Version https://github.com/immich-app/base-images/blob/main/postgres/versions.yaml
	# and https://github.com/mmomjian/immich/blob/main/server/src/constants.ts#L24
	amd64.url = "https://github.com/tensorchord/VectorChord/releases/download/1.1.1/postgresql-17-vchord_1.1.1-1_amd64.deb"
	amd64.sha256 = "a48132c8d616c0d52a9811b32f12f88a8f6cc8542d7cc0180c8d0986bfbd03c5"
	arm64.url = "https://github.com/tensorchord/VectorChord/releases/download/1.1.1/postgresql-17-vchord_1.1.1-1_arm64.deb"
	arm64.sha256 = "50ae776bb2376f2b21aea646984cef51e96cc8ae49626cceccb043432c3ba1aa"

	format = "whatever"
	extract = false
	rename = "postgresql-17-vchord.deb"
	prefetch = true

	[resources.system_user]

	[resources.install_dir]

	[resources.data_dir]

	[resources.permissions]
	main.url = "/"
	api.url = "/api"
	api.allowed = "visitors"
	api.show_tile = false
	api.protected = true

	[resources.ports]
	main.default = 2283
	machinelearning.default = 3003

	[resources.apt]
	packages = [
		"postgresql",
		"redis-server",
		"uuid-runtime",
		"curl",
		"unzip",
		"libgl1",
		"libglib2.0-0",
		"libexpat1",
		"libexif12",
		"libgif7",
		"libjpeg62-turbo",
		"libpng16-16",
		"libwebp7",
		"libtiff6",
		"libcgif0",
		"liblcms2-2",
		"libaom3",
		"libde265-0",
		"libimagequant0",
		"libwebpdemux2"
	]
	packages_from_raw_bash = """
	if [[ $YNH_DEBIAN_VERSION == "trixie" ]]; then
		echo "libdav1d7, libraw23t64, postgresql-17-pgvector";
	elif [[ $YNH_DEBIAN_VERSION == "bookworm" ]]; then
		echo "libdav1d6, libraw20";
	fi
	"""

	[resources.apt.extras.jellyfin-ffmpeg]
	repo = "deb https://repo.jellyfin.org/debian __YNH_DEBIAN_VERSION__ main"
	key = "https://repo.jellyfin.org/jellyfin_team.gpg.key"
	packages = [
		"jellyfin-ffmpeg7"
	]

	[resources.database]
	type = "postgresql"

	[resources.nodejs]
	version = "24.15.0"
