#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "immich"
name = "Immich"
description.en = "Photo and video backup solution directly from your mobile phone"
description.fr = "Sauvegarde de photos et de vidéos directement depuis votre mobile"

version = "2.5.6~ynh5"

maintainers = ["ewilly"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://immich.app"
demo = "https://demo.immich.app"
admindoc = "https://github.com/immich-app/immich#getting-started"
userdoc = "https://github.com/immich-app/immich#getting-started"
code = "https://github.com/immich-app/immich"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["amd64"]
multi_instance = false

ldap = false
sso = false

disk = "3G"
ram.build = "2G"
ram.runtime = "2G"

[install]
	[install.domain]
	type = "domain"

	[install.init_main_permission]
	type = "group"
	default = "visitors"

[resources]
	[resources.sources]

	[resources.sources.immich_prebuilt_bookworm]
	amd64.url = "https://github.com/YunoHost-Apps/immich_ynh/releases/download/immich-v2.5.6/immich-v2.5.6-bookworm-amd64.tar.gz"
	amd64.sha256 = "5e5d818b528244036749b4db3987f2d74760225a1ce08175ace2ad21a80be51f"

	prefetch = false

	[resources.sources.immich_prebuilt_trixie]
	amd64.url = "https://github.com/YunoHost-Apps/immich_ynh/releases/download/immich-v2.5.6/immich-v2.5.6-trixie-amd64.tar.gz"
	amd64.sha256 = "ddb8c93054d9836f1fd0b8cd6f0cafd6dca8dd5cdec94150be04a66598bc3dee"

	prefetch = false

    [resources.sources.vchord]
	# Version https://github.com/immich-app/base-images/blob/main/postgres/versions.yaml
	amd64.url = "https://github.com/tensorchord/VectorChord/releases/download/0.5.3/postgresql-17-vchord_0.5.3-1_amd64.deb"
	amd64.sha256 = "d27910baaf86de52af19e25a9d6198dfecf1dbe50864075b0a9386cdc7de2c9b"

	format = "whatever"
	extract = false
	rename = "postgresql-17-vchord.deb"
	prefetch = true

	[resources.system_user]

	[resources.install_dir]

	[resources.data_dir]

	[resources.permissions]
	main.url = "/"
	api.url = "/api"
	api.allowed = "visitors"
	api.show_tile = false
	api.protected = true

	[resources.ports]
	main.default = 2283
	machinelearning.default = 3003

	[resources.apt]
	packages = [
		"postgresql",
		"redis-server",
		"uuid-runtime",		
		"curl",
		"unzip",
		"libglib2.0-0",
		"libexpat1",
		"libexif12",
		"libgif7",
		"libjpeg62-turbo",
		"libpng16-16",
		"libwebp7",
		"libtiff6",
		"libcgif0",
		"liblcms2-2",
		"libdav1d6",
		"libaom3",
		"libde265-0
	]
	packages_from_raw_bash = """
	if [[ $YNH_DEBIAN_VERSION == "trixie" ]]; then
		echo "postgresql-17-pgvector";
	fi
	"""

	[resources.apt.extras.jellyfin-ffmpeg]
	repo = "deb https://repo.jellyfin.org/debian __YNH_DEBIAN_VERSION__ main"
	key = "https://repo.jellyfin.org/jellyfin_team.gpg.key"
	packages = [
		"jellyfin-ffmpeg7"
	]

	[resources.database]
	type = "postgresql"

	[resources.nodejs]
	version = "24.12.0"
