#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..." --weight=1

ynh_systemd_action --service_name=$app-server --action="stop" --log_path="/var/log/$app/$app-server.log"
ynh_systemd_action --service_name=$app-microservices --action="stop" --log_path="/var/log/$app/$app-microservices.log"
ynh_systemd_action --service_name=$app-ml --action="stop" --log_path="/var/log/$app/$app-ml.log"
ynh_systemd_action --service_name=$app-web --action="stop" --log_path="/var/log/$app/$app-web.log"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression --message="Updating NGINX web server configuration..." --weight=1

ynh_change_url_nginx_config

#=================================================
# GENERIC FINALISATION
#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

ynh_systemd_action --service_name=$app-server --action="start" --log_path="/var/log/$app/$app-server.log"
ynh_systemd_action --service_name=$app-microservices --action="start" --log_path="/var/log/$app/$app-microservices.log"
ynh_systemd_action --service_name=$app-ml --action="start" --log_path="/var/log/$app/$app-ml.log"
ynh_systemd_action --service_name=$app-web --action="start" --log_path="/var/log/$app/$app-web.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Change of URL completed for $app" --last
