#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app-server" >/dev/null; then
	yunohost service remove "$app-server"
fi
if ynh_hide_warnings yunohost service status "$app-microservices" >/dev/null; then
	yunohost service remove "$app-microservices"
fi
if ynh_hide_warnings yunohost service status "$app-machine-learning" >/dev/null; then
	yunohost service remove "$app-machine-learning"
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd "immich-server"
ynh_config_remove_systemd "immich-microservices"
ynh_config_remove_systemd "immich-machine-learning"

# Remove the app-specific fail2ban config
ynh_config_remove_fail2ban

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove database
myynh_drop_psql_db

# Remove dependencies
ynh_nodejs_remove

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Removal of $app completed"
