# This workflow allows GitHub Actions to automagically update your app whenever a new upstream release is detected.
# You need to enable Actions in your repository settings, and fetch this Action from the YunoHost-Apps organization.
# This file should be enough by itself, but feel free to tune it to your needs.
# It calls updater.sh, which is where you should put the app-specific update steps.
name: Check for new ffmpeg-static releases
on:
  # Allow to manually trigger the workflow
  workflow_dispatch:
  # Run it every day at 6:00 UTC
  schedule:
    - cron:  '0 6 * * *'
jobs:
  updater:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the source code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install yq/tomlq
        id: install_yq
        run: pip install yq
      - name: Run the updater script
        id: run_updater
        run: |
          # Setting up Git user
          git config --global user.name 'yunohost-bot'
          git config --global user.email 'yunohost-bot@users.noreply.github.com'
          # Run the updater script
          /bin/bash .github/workflows/updater_ffmpeg-static.sh
      - name: Commit changes
        id: commit
        if: ${{ env.PROCEED == 'true' }}
        run: |
          git commit -am "Update ffmpeg-static sha for $VERSION"
      - name: Create Pull Request to testing
        id: cpr-testing
        if: ${{ env.PROCEED == 'true' }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update ffmpeg-static sha for ${{ env.VERSION }}
          committer: 'yunohost-bot <yunohost-bot@users.noreply.github.com>'
          author: 'yunohost-bot <yunohost-bot@users.noreply.github.com>'
          signoff: false
          base: testing
          branch: ci-auto-update-ffmpeg-static-sha-${{ env.VERSION }}
          delete-branch: true
          title: 'Update ffmpeg-static sha for ${{ env.VERSION }}'
          body: |
            Update ffmpeg-static sha for ${{ env.VERSION }}
          draft: false
